version: '3.3'

services:
  web:
    image: nginx:latest
    working_dir: /var/www/html
    ports:
        - 8000:80
    volumes:
        - ./project:/var/www/html
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    build: ./docker/php
    volumes:
      - ./project:/var/www/html
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sendpulse
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
